name: transmission

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '4.0.3'
      web_version:
        description: 'Web Control version'
        required: true
        default: '1.6.1-update1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        id: prepare
        run: |
          VERSION=${{ github.event.inputs.version }}
          WEB_VERSION=${{ github.event.inputs.web_version }}
          IMAGE_NAME=transmission
          TAGS="gists/${IMAGE_NAME}:${VERSION},gists/${IMAGE_NAME}:latest"
          echo "build_args1=VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "build_args2=WEB_VERSION=${WEB_VERSION}" >> $GITHUB_OUTPUT
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: ./${{ steps.prepare.outputs.image-name }}
          file: ./${{ steps.prepare.outputs.image-name }}/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/ppc64le,linux/s390x
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            ${{ steps.prepare.outputs.build_args1 }}
            ${{ steps.prepare.outputs.build_args2 }}
          tags: ${{ steps.prepare.outputs.tags }}
